In [1]:
import pandas as pd

In [2]:
animals = pd.read_csv("../data/animals.csv")
animals.head()

       Name Type         Breed     Outcome Type  Days in Shelter
0      REMY  DOG        BEAGLE  RETURN TO OWNER                3
1    *RONDE  DOG  CHIHUAHUA SH         ADOPTION               49
2    *SNOOP  CAT   DOMESTIC SH         ADOPTION               38
3      FIFI  CAT       SIAMESE         ADOPTION                6
4  CINNAMON  DOG      PIT BULL  RETURN TO OWNER                1

In [3]:
animals['Type'].value_counts()

Type
DOG      12265
CAT       7771
OTHER     1761
Name: count, dtype: int64

In [4]:
animals.groupby('Type')['Days in Shelter'].mean()
animals.groupby('Type').agg({'Days in Shelter':'mean'})

       Days in Shelter
Type
CAT          16.279629
DOG          17.318956
OTHER        20.914821

In [5]:
animals.groupby('Type')['Outcome Type'].describe()

       count unique              top  freq
Type
CAT     7712      9         ADOPTION  3303
DOG    12182      9  RETURN TO OWNER  6138
OTHER   1727      7         TRANSFER   759

In [6]:
animals[animals['Type']=='OTHER']['Breed'].unique()

array(['POLISH', 'REX', 'RABBIT LH', 'CHICKEN', 'BAT', 'RABBIT SH',
       'BARRED ROCK', 'HORSE', 'MULE', 'GUINEA PIG', 'SHEEP', 'COCKATIEL',
       'GOAT', 'LIZARD', 'AMERICAN', 'LOP-MINI', 'TORTOISE', 'PAINT',
       'BUDGERIGAR', 'ANGUS', 'DUCK', 'NEW ZEALAND WHT/MIX',
       'LOP-ENGLISH', 'NETHERLND DWARF', 'MUSCOVY', 'PARAKEET', 'PIG',
       'HOTOT', 'HOTOT/MIX', 'ARAUCANA', 'GOOSE', 'HAWK', 'FLORIDA WHITE',
       'CALIFORNIAN', 'OPOSSUM', 'PEAFOWL', 'RABBIT LH/MIX',
       'NEW ZEALAND WHT', 'ENGLISH SPOT', 'RAT', 'REX/MIX', 'SKUNK',
       'JACK', 'LOP-FRENCH', 'DUTCH/MIX', 'APPALOOSA', 'ANGORA-SATIN/MIX',
       'FERRET', 'HARLEQUIN/MIX', 'POTBELLY PIG', 'ANGORA-ENGLISH',
       'DUCK/CAYUGA', 'RACCOON', 'SQUIRREL', 'GOAT/LA MANCHA', 'PIGEON',
       'FLEMISH GIANT', 'GOAT/BOER', 'LOP-HOLLAND/MIX', 'LOVEBIRD',
       'HAVANA/MIX', 'KOI', 'HAMSTER', 'TURTLE', 'PALOMINO', 'SNAKE',
       'BOER', 'ENGLISH SPOT/MIX', 'TROPICAL', 'LOP-ENGLISH/MIX',
       'CANARY', 'DUTCH', 'MOUSE', 'RHODE ISLAND', 'CALIFORNIAN/MIX',
       'MACAW', 'DWARF HOTOT', 'PERUVIAN PASO', 'BANTAM', 'JERSEY/MIX',
       'DONKEY', 'GOAT/ALPINE', 'LOP-HOLLAND', 'JERSEY', 'DOVE',
       'GOAT/PYGMY', 'FINCH', 'ARABIAN', 'GOAT/NUBIAN', 'QUARTER HORSE',
       'AMERICAN SABLE/MIX', 'PALOMINO/MIX', 'FOX', 'HIMALAYAN/MIX',
       'COLD WATER', 'REX-MINI/MIX', 'LA MANCHA', 'DEGU',
       'LOP-AMER FUZZY', 'PARROT', 'AMERICAN/REX',
       'ANGORA-FRENCH/FLEMISH GIANT', 'CHICKEN/BANTAM', 'COCKATOO',
       'TURKEY', 'SILVER', 'LOP-MINI/MIX', 'NETHERLND DWARF/MIX', 'LILAC',
       'RHINELANDER/MIX', 'LEGHORN', 'SILVER/MIX', 'ANGORA-SATIN',
       'LLAMA', 'CONURE', 'THOROUGHBRED', 'CHINCHILLA', 'PYGMY',
       'OTHER BIRD', 'SHETLAND', 'QUAIL', 'CHAMPGN DARGENT',
       'LOP-AMER FUZZY/MIX', 'PONY', 'HERON', 'ALPINE/MIX'], dtype=object)

In [7]:
animals.groupby("Breed")['Days in Shelter'].mean().sort_values(ascending=False).head(1)

Breed
CAROLINA DOG/MIX    314.0
Name: Days in Shelter, dtype: float64

In [8]:
animals_filtered = animals['Breed'].value_counts()
breed_filter = animals_filtered[animals_filtered >= 100].index.to_list()
animals[animals['Breed'].isin(breed_filter)].groupby('Breed')['Days in Shelter'].mean().sort_values()

Breed
BAT                     0.600000
LABRADOR RETR           5.535088
POODLE MIN              7.730769
ROTTWEILER              7.861789
SIAMESE                11.610063
PARSON RUSS TER        11.869231
BORDER COLLIE/MIX      12.828025
CAIRN TERRIER/MIX      12.877193
LABRADOR RETR/MIX      13.450794
GERM SHEPHERD          14.395619
SIBERIAN HUSKY         15.286145
POODLE MIN/MIX         15.538462
PARSON RUSS TER/MIX    15.645000
DOMESTIC LH            15.783828
DOMESTIC MH            15.936228
DOMESTIC SH            16.456838
CHIHUAHUA SH/MIX       16.949597
SIAMESE/MIX            17.968750
GERM SHEPHERD/MIX      18.329305
CHIHUAHUA SH           18.891429
RABBIT SH              24.429825
PIT BULL               25.487477
PIT BULL/MIX           27.520223
CHICKEN                29.022364
BORDER COLLIE          30.000000
Name: Days in Shelter, dtype: float64

In [9]:
animals['Breed'].value_counts()[lambda x: x >= 100]

Breed
DOMESTIC SH            5989
PIT BULL               1637
CHIHUAHUA SH           1050
GERM SHEPHERD           776
DOMESTIC MH             737
PIT BULL/MIX            717
DOMESTIC LH             606
CHIHUAHUA SH/MIX        496
LABRADOR RETR           456
RABBIT SH               342
SIBERIAN HUSKY          332
GERM SHEPHERD/MIX       331
LABRADOR RETR/MIX       315
CHICKEN                 313
PARSON RUSS TER/MIX     200
BAT                     180
SIAMESE                 159
BORDER COLLIE/MIX       157
PARSON RUSS TER         130
SIAMESE/MIX             128
ROTTWEILER              123
CAIRN TERRIER/MIX       114
BORDER COLLIE           107
POODLE MIN/MIX          104
POODLE MIN              104
Name: count, dtype: int64

In [10]:
animals.groupby('Breed')['Days in Shelter'].agg(['mean', 'count'])[lambda row: row['count'] >= 100].sort_values('mean')

                          mean  count
Breed
BAT                   0.600000    180
LABRADOR RETR         5.535088    456
POODLE MIN            7.730769    104
ROTTWEILER            7.861789    123
SIAMESE              11.610063    159
PARSON RUSS TER      11.869231    130
BORDER COLLIE/MIX    12.828025    157
CAIRN TERRIER/MIX    12.877193    114
LABRADOR RETR/MIX    13.450794    315
GERM SHEPHERD        14.395619    776
SIBERIAN HUSKY       15.286145    332
POODLE MIN/MIX       15.538462    104
PARSON RUSS TER/MIX  15.645000    200
DOMESTIC LH          15.783828    606
DOMESTIC MH          15.936228    737
DOMESTIC SH          16.456838   5989
CHIHUAHUA SH/MIX     16.949597    496
SIAMESE/MIX          17.968750    128
GERM SHEPHERD/MIX    18.329305    331
CHIHUAHUA SH         18.891429   1050
RABBIT SH            24.429825    342
PIT BULL             25.487477   1637
PIT BULL/MIX         27.520223    717
CHICKEN              29.022364    313
BORDER COLLIE        30.000000    107

In [25]:
animals["Outcome Type"].value_counts(normalize=True).loc['ADOPTION']

np.float64(0.3079876046436335)

In [46]:
pd.crosstab(animals['Breed'], animals['Outcome Type'], normalize="index")['ADOPTION'].nlargest(1, keep="all")

Breed
AKITA/ALASKAN HUSKY              1.0
ALASKAN HUSKY/AUST SHEPHERD      1.0
AM PIT BULL TER/LABRADOR RETR    1.0
AMER BULLDOG/AM PIT BULL TER     1.0
AMER FOXHOUND/WHIPPET            1.0
                                ...
VIZSLA/LABRADOR RETR             1.0
WELSH CORGI PEM/CHIHUAHUA SH     1.0
WELSH TERRIER/MIX                1.0
YORKSHIRE TERR/BRUSS GRIFFON     1.0
YORKSHIRE TERR/FOX TERR WIRE     1.0
Name: ADOPTION, Length: 138, dtype: float64

In [49]:
animals['adopted'] = animals['Outcome Type'] == "ADOPTION"
animals.groupby("Breed")['adopted'].mean()

Breed
ABYSSINIAN                        0.000000
ABYSSINIAN/MIX                    0.800000
AFFENPINSCHER                     0.142857
AFFENPINSCHER/MIX                 0.000000
AIREDALE TERR                     0.000000
                                    ...
YORKSHIRE TERR/PARSON RUSS TER    0.000000
YORKSHIRE TERR/POMERANIAN         0.000000
YORKSHIRE TERR/POODLE MIN         0.000000
YORKSHIRE TERR/POODLE TOY         0.000000
YORKSHIRE TERR/SCHNAUZER MIN      0.000000
Name: adopted, Length: 974, dtype: float64

In [50]:
animals.groupby("Breed")['Outcome Type'].agg(lambda outcome: (outcome == "ADOPTION").mean())

Breed
ABYSSINIAN                        0.000000
ABYSSINIAN/MIX                    0.800000
AFFENPINSCHER                     0.142857
AFFENPINSCHER/MIX                 0.000000
AIREDALE TERR                     0.000000
                                    ...
YORKSHIRE TERR/PARSON RUSS TER    0.000000
YORKSHIRE TERR/POMERANIAN         0.000000
YORKSHIRE TERR/POODLE MIN         0.000000
YORKSHIRE TERR/POODLE TOY         0.000000
YORKSHIRE TERR/SCHNAUZER MIN      0.000000
Name: Outcome Type, Length: 974, dtype: float64