# pandas Basics

In this notebook, we will see some of the basic data exploration tools from the pandas library. 

We'll be using the [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/articles/intro.html) dataset, which contains size measurements for three penguin species observed on three islands in the Palmer Archipelago of Antarctica.

In [1]:
import pandas as pd

#### Importing Data

In [2]:
penguins = pd.read_csv('../data/penguins.csv')

#### Inspecting Data

The .head and .tail methods let us view the top or bottom of a DataFrame.

In [3]:
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [4]:
penguins.tail(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
334,Chinstrap,Dream,50.2,18.8,202.0,3800.0,male,2009
335,Chinstrap,Dream,45.6,19.4,194.0,3525.0,female,2009
336,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

It's also not a bad idea to look at a random sample of rows.

In [5]:
penguins.sample(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
244,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,female,2009
251,Gentoo,Biscoe,51.1,16.5,225.0,5250.0,male,2009
334,Chinstrap,Dream,50.2,18.8,202.0,3800.0,male,2009
61,Adelie,Biscoe,41.3,21.1,195.0,4400.0,male,2008
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,female,2008

In [6]:
penguins.shape

(344, 8)

This dataset has 344 rows and 8 columns.

In [7]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), object(3)
memory usage: 21.6+ KB

If pandas can't make a column into a numeric type (float or int), it will convert it to an object type.

#### Modifying

You can change column names using the rename method.

In [8]:
penguins.rename(columns={'year': 'observation_year'})

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,observation_year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

Let's check the results.

In [9]:
penguins.head(1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007

**Important:** If you want your changes to stick, you need to assign the result back to the DataFrame.

In [10]:
penguins = penguins.rename(columns={'year': 'observation_year'})

In [11]:
penguins.head(1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,observation_year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007

Similarly, we can drop unneeded columns.

In [12]:
penguins.drop(columns=['bill_length_mm'])

,species,island,bill_depth_mm,flipper_length_mm,body_mass_g,sex,observation_year
0,Adelie,Torgersen,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,18.7,198.0,3775.0,female,2009

#### Summarizing

In [13]:
penguins['species'].unique()

array(['Adelie', 'Gentoo', 'Chinstrap'], dtype=object)

In [14]:
penguins['observation_year'].nunique()

3

If we want to know how many times each value appears, we can use value_counts.

In [15]:
penguins['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

For numeric variables, we can get summary statistics using describe.

In [16]:
penguins['body_mass_g'].describe()

count     342.000000
mean     4201.754386
std       801.954536
min      2700.000000
25%      3550.000000
50%      4050.000000
75%      4750.000000
max      6300.000000
Name: body_mass_g, dtype: float64

#### Slicing and Filtering

We can use .loc to **filter** our DataFrame to rows of interest.

A common way of doing this is to write a condition describing the rows that we want to keep. For example, if we want to look at rows for the chinstrap species.

In [17]:
penguins['species'] == 'Chinstrap'

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: species, Length: 344, dtype: bool

We can then pass this to .loc.

In [18]:
penguins.loc[penguins['species'] == 'Chinstrap']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,observation_year
276,Chinstrap,Dream,46.5,17.9,192.0,3500.0,female,2007
277,Chinstrap,Dream,50.0,19.5,196.0,3900.0,male,2007
278,Chinstrap,Dream,51.3,19.2,193.0,3650.0,male,2007
279,Chinstrap,Dream,45.4,18.7,188.0,3525.0,female,2007
280,Chinstrap,Dream,52.7,19.8,197.0,3725.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

You can also specify which columns to keep. In general you will do

df.loc[rows to keep, columns to keep]

In [19]:
penguins.loc[penguins['species'] == 'Chinstrap', ['body_mass_g', 'sex']]

     body_mass_g     sex
276       3500.0  female
277       3900.0    male
278       3650.0    male
279       3525.0  female
280       3725.0    male
..           ...     ...
339       4000.0    male
340       3400.0  female
341       3775.0    male
342       4100.0    male
343       3775.0  female

[68 rows x 2 columns]

Or to keep all rows and just those two columns.

In [20]:
penguins.loc[:, ['body_mass_g', 'sex']]

     body_mass_g     sex
0         3750.0    male
1         3800.0  female
2         3250.0  female
3            NaN     NaN
4         3450.0  female
..           ...     ...
339       4000.0    male
340       3400.0  female
341       3775.0    male
342       4100.0    male
343       3775.0  female

[344 rows x 2 columns]

It is also common to select columns using just double square brackets.

In [21]:
penguins[['body_mass_g', 'sex']]

     body_mass_g     sex
0         3750.0    male
1         3800.0  female
2         3250.0  female
3            NaN     NaN
4         3450.0  female
..           ...     ...
339       4000.0    male
340       3400.0  female
341       3775.0    male
342       4100.0    male
343       3775.0  female

[344 rows x 2 columns]